version: '3.8'

services:
  # Servicio para el back-end de Node.js
  backend:
    build:
      context: ./backend  # Ruta al Dockerfile del back-end
    ports:
      - "3001:3001" # Mapea el puerto del contenedor al puerto del host
    volumes:
      - ./backend:/app # Sincroniza el código local con el del contenedor para desarrollo
      - /app/node_modules # Evita sobrescribir la carpeta de dependencias
    container_name: liverpool-backend
    depends_on:
      - db # Asegura que la base de datos se inicie primero

  # Servicio para el front-end de React
  frontend:
    build:
      context: ./frontend # Ruta al Dockerfile del front-end
    ports:
      - "3000:3000" # Mapea el puerto del contenedor al puerto del host
    volumes:
      - ./frontend:/app # Sincroniza el código local para desarrollo
      - /app/node_modules # Evita sobrescribir la carpeta de dependencias
    container_name: liverpool-frontend
    depends_on:
      - backend # Asegura que el back-end esté listo antes que el front-end

  # Servicio para la base de datos MySQL
  db:
    image: mysql:8.0 # Utiliza la imagen oficial de MySQL
    container_name: liverpool-db
    environment:
      MYSQL_ROOT_PASSWORD: tu_password_segura # ¡Cambia esto por una contraseña real!
      MYSQL_DATABASE: liverpool_db # Nombre de la base de datos
    ports:
      - "3306:3306" # Mapea el puerto de la base de datos
    volumes:
      - db_data:/var/lib/mysql # Persiste los datos de la base de datos en el volumen
      
# Definición de volúmenes para persistir los datos
volumes:
  db_data: